# Generated by Django 4.2.7 on 2024-03-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_Picture',
            field=models.ImageField(default=1, upload_to='uploads/'),
        ),
    ]
