# Generated by Django 4.2.7 on 2024-03-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Servicess',
        ),
    ]
