# Generated by Django 4.2.7 on 2024-03-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_servicess_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
