# Generated by Django 4.2.7 on 2024-03-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_service_services_alter_services_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
